name: openarm_genesis
channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.12
  - pip:
      - click==8.1.8
      - coacd==1.0.5
      - genesis-world==0.2.1
      - numba==0.61.0
      - numpy==1.26.4
      - opencv-python==4.11.0.86
      - pymeshlab
      - pyopengl==3.1.9
      - taichi==1.7.3
      - torch==2.6.0
      - torchvision==0.21.0
